export const config = { runtime: 'edge' };

// ── HTML EMAIL TEMPLATES ─────────────────────────────────────────────────────
function wrapEmail(title, accentColor, body) {
  return `<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="margin:0;padding:0;background:#f1f5f9;font-family:'Segoe UI',Arial,sans-serif">
<table width="100%" cellpadding="0" cellspacing="0" style="background:#f1f5f9;padding:32px 16px">
<tr><td align="center">
<table width="600" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:12px;overflow:hidden;border:1px solid #e2e8f0">
  <tr><td style="background:${accentColor};padding:24px 32px">
    <p style="margin:0;font-family:'Courier New',monospace;font-size:11px;color:rgba(255,255,255,.7);letter-spacing:2px;text-transform:uppercase">RMF EXPERT PLATFORM</p>
    <h1 style="margin:8px 0 0;color:#ffffff;font-size:22px;font-weight:700">${title}</h1>
  </td></tr>
  <tr><td style="padding:32px">${body}</td></tr>
  <tr><td style="background:#f8fafc;padding:16px 32px;border-top:1px solid #e2e8f0">
    <p style="margin:0;font-size:11px;color:#94a3b8;font-family:'Courier New',monospace">Generated by RMF Expert Platform · ${new Date().toUTCString()}</p>
  </td></tr>
</table>
</td></tr></table></body></html>`;
}

function severityBadge(sev) {
  const colors = { CRITICAL:'#991b1b', HIGH:'#c2410c', MEDIUM:'#92400e', LOW:'#166534' };
  const bg = { CRITICAL:'#fee2e2', HIGH:'#fff7ed', MEDIUM:'#fffbeb', LOW:'#f0fdf4' };
  const s = (sev || 'UNKNOWN').toUpperCase();
  return `<span style="display:inline-block;padding:3px 10px;border-radius:4px;background:${bg[s]||'#f1f5f9'};color:${colors[s]||'#334155'};font-family:'Courier New',monospace;font-size:12px;font-weight:700;border:1px solid ${colors[s]||'#94a3b8'}">${s}</span>`;
}

function field(label, value) {
  return `<tr>
    <td style="padding:8px 12px;background:#f8fafc;font-size:12px;font-family:'Courier New',monospace;color:#475569;font-weight:600;white-space:nowrap;border:1px solid #e2e8f0;width:160px">${label}</td>
    <td style="padding:8px 12px;font-size:13px;color:#0f172a;border:1px solid #e2e8f0">${value||'—'}</td>
  </tr>`;
}

function buildCVEHtml(data) {
  const { cveId, severity, score, description, affected, published, aiDraft, customNote } = data;
  return wrapEmail(`Security Vulnerability Alert — ${cveId}`, '#1e3a5f',
    `<p style="margin:0 0 20px;font-size:14px;color:#334155;line-height:1.6">This is a formal security notification regarding a newly published vulnerability that may affect systems under your purview. Please review and take appropriate action.</p>
    <table width="100%" cellpadding="0" cellspacing="0" style="margin-bottom:24px;border-collapse:collapse">
      ${field('CVE ID', `<strong>${cveId}</strong>`)}
      ${field('Severity', severityBadge(severity))}
      ${field('CVSS Score', score ? `<strong>${score} / 10.0</strong>` : '—')}
      ${field('Affected Product', affected||'See description')}
      ${field('Published', published||'—')}
    </table>
    <h3 style="margin:0 0 8px;font-size:14px;color:#1e3a5f;font-family:'Courier New',monospace;letter-spacing:1px">VULNERABILITY DESCRIPTION</h3>
    <p style="margin:0 0 24px;font-size:13px;color:#334155;line-height:1.7;background:#f8fafc;padding:14px;border-left:3px solid #1e3a5f;border-radius:4px">${description||'See NVD for full description.'}</p>
    ${aiDraft ? `<h3 style="margin:0 0 8px;font-size:14px;color:#1e3a5f;font-family:'Courier New',monospace;letter-spacing:1px">ANALYSIS &amp; RECOMMENDED ACTIONS</h3><div style="font-size:13px;color:#0f172a;line-height:1.75;margin-bottom:24px">${aiDraft.replace(/\n/g,'<br>')}</div>` : ''}
    ${customNote ? `<div style="background:#fffbeb;border:1px solid #fcd34d;border-radius:6px;padding:14px;margin-bottom:24px"><p style="margin:0;font-size:13px;color:#92400e;line-height:1.6">${customNote}</p></div>` : ''}
    <p style="margin:0;font-size:13px;color:#475569">Please acknowledge receipt of this notification and confirm the status of affected systems within <strong>72 hours</strong>. Contact the ISSO with any questions.</p>`
  );
}

function buildPOAMHtml(data) {
  const { findingId, title, cat, severity, status, description, fix, requestType, dueDate, justification, aiDraft } = data;
  const isExtension = requestType === 'extension';
  const accentColor = isExtension ? '#92400e' : '#991b1b';
  const typeLabel = isExtension ? 'POA&M Extension Request' : 'Risk Acceptance Request';
  return wrapEmail(`${typeLabel} — ${findingId}`, accentColor,
    `<p style="margin:0 0 20px;font-size:14px;color:#334155;line-height:1.6">${isExtension
      ? 'A request to extend the remediation milestone for the following Plan of Action and Milestone (POA&M) item is submitted for your review and approval.'
      : 'A formal request for acceptance of residual risk associated with the following security finding is submitted for Authorizing Official review.'}</p>
    <table width="100%" cellpadding="0" cellspacing="0" style="margin-bottom:24px;border-collapse:collapse">
      ${field('Finding ID', `<strong>${findingId}</strong>`)}
      ${field('Rule Title', title||'—')}
      ${field('Category', `<strong>${cat}</strong>`)}
      ${field('Severity', severityBadge(severity))}
      ${field('Current Status', status||'Open')}
      ${isExtension ? field('Proposed New Date', dueDate||'See justification') : ''}
    </table>
    <h3 style="margin:0 0 8px;font-size:14px;color:#1e3a5f;font-family:'Courier New',monospace;letter-spacing:1px">VULNERABILITY DESCRIPTION</h3>
    <p style="margin:0 0 20px;font-size:13px;color:#334155;line-height:1.7;background:#f8fafc;padding:14px;border-left:3px solid ${accentColor};border-radius:4px">${description||'—'}</p>
    ${aiDraft ? `<h3 style="margin:0 0 8px;font-size:14px;color:#1e3a5f;font-family:'Courier New',monospace;letter-spacing:1px">${isExtension ? 'EXTENSION JUSTIFICATION' : 'RISK ACCEPTANCE JUSTIFICATION'}</h3><div style="font-size:13px;color:#0f172a;line-height:1.75;margin-bottom:20px">${aiDraft.replace(/\n/g,'<br>')}</div>` : ''}
    ${justification ? `<div style="background:#fff7ed;border:1px solid #fed7aa;border-radius:6px;padding:14px;margin-bottom:24px"><p style="margin:0;font-size:13px;color:#92400e;line-height:1.6"><strong>Additional Note:</strong> ${justification}</p></div>` : ''}
    <div style="background:#f8fafc;border:1px solid #e2e8f0;border-radius:8px;padding:16px;margin-top:24px">
      <p style="margin:0 0 6px;font-size:12px;font-family:'Courier New',monospace;color:#475569;letter-spacing:1px">SIGNATURE BLOCK</p>
      <p style="margin:0;font-size:13px;color:#0f172a">Authorizing Official: ____________________________</p>
      <p style="margin:8px 0 0;font-size:13px;color:#0f172a">Signature: __________________ Date: ______________</p>
    </div>`
  );
}

function buildIntakeHtml(data) {
  const { name, email, org, role, source, useCase } = data;
  return wrapEmail('New Access Request — RMF Expert', '#1e3a5f',
    `<p style="margin:0 0 20px;font-size:14px;color:#334155">Someone has submitted an access request through your RMF Expert platform.</p>
    <table width="100%" cellpadding="0" cellspacing="0" style="margin-bottom:24px;border-collapse:collapse">
      ${field('Name', name)} ${field('Email', email)}
      ${field('Organization', org)} ${field('Role / Title', role)}
      ${field('How They Found It', source)}
    </table>
    <h3 style="margin:0 0 8px;font-size:14px;color:#1e3a5f;font-family:'Courier New',monospace;letter-spacing:1px">USE CASE / INTEREST</h3>
    <p style="margin:0 0 24px;font-size:13px;color:#334155;line-height:1.7;background:#f8fafc;padding:14px;border-left:3px solid #1e3a5f;border-radius:4px">${useCase||'Not provided'}</p>
    <p style="font-size:13px;color:#475569">To grant access, share your site password with this person directly. To deny, no action is needed.</p>`
  );
}

// ── MAIN HANDLER ─────────────────────────────────────────────────────────────
export default async function handler(req) {
  if (req.method !== 'POST')
    return new Response(JSON.stringify({ error: 'Method not allowed' }), { status: 405, headers: { 'Content-Type': 'application/json' } });

  const resendKey  = process.env.RESEND_API_KEY;
  const fromEmail  = process.env.EMAIL_FROM;
  const ownerEmail = process.env.OWNER_EMAIL;

  if (!resendKey || !fromEmail)
    return new Response(JSON.stringify({ error: 'RESEND_API_KEY and EMAIL_FROM must be set in Vercel Environment Variables.' }), { status: 500, headers: { 'Content-Type': 'application/json' } });

  let body;
  try { body = await req.json(); }
  catch { return new Response(JSON.stringify({ error: 'Invalid JSON' }), { status: 400, headers: { 'Content-Type': 'application/json' } }); }

  const { type } = body;

  // Intake form — no session required, anyone can submit
  if (type === 'intake') {
    if (!ownerEmail)
      return new Response(JSON.stringify({ error: 'OWNER_EMAIL not set. Add your email in Vercel Environment Variables.' }), { status: 500, headers: { 'Content-Type': 'application/json' } });
    const html = buildIntakeHtml(body);
    const res = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${resendKey}` },
      body: JSON.stringify({ from: fromEmail, to: [ownerEmail], subject: `[RMF Expert] Access Request — ${body.name} (${body.org})`, html }),
    });
    const data = await res.json();
    if (!res.ok) return new Response(JSON.stringify({ error: data?.message || 'Failed to send.' }), { status: res.status, headers: { 'Content-Type': 'application/json' } });
    return new Response(JSON.stringify({ success: true }), { status: 200, headers: { 'Content-Type': 'application/json' } });
  }

  // Outbound emails — session required
  const sitePassword = process.env.SITE_PASSWORD;
  if (sitePassword) {
    const token = req.headers.get('X-Session-Token') || '';
    if (token !== btoa('authenticated:' + sitePassword))
      return new Response(JSON.stringify({ error: 'Session expired. Please refresh and log in.' }), { status: 401, headers: { 'Content-Type': 'application/json' } });
  }

  const { recipients, subject } = body;
  if (!recipients?.length || !subject)
    return new Response(JSON.stringify({ error: 'Recipients and subject are required.' }), { status: 400, headers: { 'Content-Type': 'application/json' } });

  let html = '';
  if (type === 'cve')  html = buildCVEHtml(body);
  if (type === 'poam') html = buildPOAMHtml(body);
  if (type === 'custom') html = wrapEmail(subject, '#1e3a5f', `<div style="font-size:14px;color:#0f172a;line-height:1.8">${(body.message||'').replace(/\n/g,'<br>')}</div>`);

  if (!html)
    return new Response(JSON.stringify({ error: 'Unknown email type.' }), { status: 400, headers: { 'Content-Type': 'application/json' } });

  const res = await fetch('https://api.resend.com/emails', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${resendKey}` },
    body: JSON.stringify({ from: fromEmail, to: recipients, subject, html }),
  });
  const data = await res.json();
  if (!res.ok) return new Response(JSON.stringify({ error: data?.message || `Resend error ${res.status}` }), { status: res.status, headers: { 'Content-Type': 'application/json' } });
  return new Response(JSON.stringify({ success: true, id: data.id }), { status: 200, headers: { 'Content-Type': 'application/json' } });
}
